# Instruments 


# Auth 
REGISTER_SUCCESS = 'REGISTER_SUCCESS'
REGISTER_FAILED = 'REGISTER_FAILED'
LOGIN_SUCCESS = 'LOGIN_SUCCESS'
LOGIN_FAILED = 'LOGIN_FAILED'
USER_LOADED = 'USER_LOADED'
AUTH_ERROR = 'AUTH_ERROR'
LOGOUT = 'LOGOUT'

# User

# Link
PROTOCOL = 'https://'
SSL = 'adhoc'
HOST = 'zooming-exploration-production.up.railway.app' # 'localhost:
PORT = 8080

# Return Codes
POST = 'POST'
GET = 'GET'

# Settings
DEBUG = True
DEPLOY = True

# Messages / Codes
MESSAGE_SENT = 'MESSAGE_SENT'
MESSAGE_FAILED = 'MESSAGE_FAILED'
MESSAGE_RECEIVED = 'MESSAGE_RECEIVED'
MESSAGE_ERROR = 'MESSAGE_ERROR'
MESSAGE_DELETED = 'MESSAGE_DELETED'
BAD_REQUEST = 400
UNAUTHORIZED = 401
OK = 200
CREATED = 201
ACCEPTED = 202
CONTENT_TYPE = 'Content-Type'
APPLICATION_JSON = 'application/json'
TEXT_HTML = 'text/html'
IMAGE_JPEG = 'image/jpeg'


